### ISSUE TITLE
[ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: MissingPluginException(No implementation found for method show on channel native_page_view_controller)

### ISSUE THREAD

**Issue by BartusZak** [river2202/flutter-native-page-view-controller#7]
I tried to run `example` project from this reposiitory but it failed (tested on andorid and web).

App compiles and runs normally until you click `Native PageViewController` button.

```
I/flutter ( 9982): screenSize=Size(392.7, 759.3), targetSize=Size(392.7, 548.3)
I/flutter ( 9982): pageRect=Rect.fromLTRB(0.0, 105.5, 392.7, 653.8)
E/flutter ( 9982): [ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: MissingPluginException(No implementation found for method show on channel native_page_view_controller)
E/flutter ( 9982): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:156:7)
E/flutter ( 9982): <asynchronous suspension>
E/flutter ( 9982): #1      NativePageViewController.show (package:native_page_view_controller/native_page_view_controller.dart:45:5)
E/flutter ( 9982): <asynchronous suspension>
E/flutter ( 9982):
```

<details>
<summary>flutter doctor -v</summary>

```
[√] Flutter (Channel stable, 2.0.3, on Microsoft Windows [Version 10.0.19042.928], locale en-US)
    • Flutter version 2.0.3 at C:\FlutterSDK\flutter
    • Framework revision 4d7946a68d (4 weeks ago), 2021-03-18 17:24:33 -0700
    • Engine revision 3459eb2436
    • Dart version 2.12.2

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\bplos\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java       
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.55.2)
    • VS Code at C:\Users\bplos\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.21.0

[√] Connected device (3 available)
    • sdk gphone x86 arm (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • Chrome (web)                • chrome        • web-javascript • Google Chrome 89.0.4389.128
    • Edge (web)                  • edge          • web-javascript • Microsoft Edge 89.0.774.68
```

</details>

<details>
<summary>Screenshoot </summary>

![image](https://user-images.githubusercontent.com/16143176/115020957-9f15a180-9ebb-11eb-9af2-9c592864a765.png)

</details>

**Comment by river2202** [comment]
The plugin only implement iOS since iOS has system implementation of page curl.

There is no plan to continue developing this plugin.

Best Regards,
River Huang

**Comment by BartusZak** [comment]
Thanks for the reply.

Have a good day :)

Pozdrawiam / Best regards

*Bartłomiej Płoszyński*

Tel: +48 792 525 864

E-mail: ***@***.***


*Nadchodzące nieobecności / przerwy w świadczeniu usług*
